### ISSUE TITLE
Do Not Disturb swallows all notifications

### ISSUE THREAD

**Issue by joedborg** [elementary/wingpanel-indicator-notifications#100]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
When setting "Do Not Disturb", no notifications are populated in the list when the indicator is opened.  This is not expected behaviour for me.  I expect the audio alert and visual notification to be suppressed, but I also expect to be able to open the indicator and see any notifications that have populated since the last time I opened it / cleared the list.

### To Reproduce
1. Turn on DND.
2. Look for notifications triggered in that time.
3. List is empty.

### Expected behavior
Notifications to be suppressed but shown in indicator.

## Platform Information
elementary OS 5.1.2 Hera
- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

**Comment by danrabbit** [comment]
I'm unable to confirm this on daily 6.0. This may have been fixed somewhere along the way. Closing for now unless someone can reproduce the issue on 6.0
