### ISSUE TITLE
Add a way to mark a notification as read without closing the main notifications window

### ISSUE THREAD

**Issue by vbuell** [elementary/wingpanel-indicator-notifications#101]
The current behavior is when you click a notification then the notification tray window closes as well. If you have many notifications there and you don't want "Clear all notifications" then it may be painful to close them one-by-one.

Should we have an alternative hotkey (Ctrl-LMB for instance) to make a notification diappear AND to keep the list opened?

**Comment by vbuell** [comment]
Interestingly enough, the indicator built from master doesn't have this issue - the LMB click removes the notification and leaves the list opened.

The version from a PPA focal repo (2.1.3+r421+pkg32~daily~ubuntu6.0.1) closes the list when item is clicked.
The master (sha: 73014302f0f4594f5436fad22c8ff10ed84a0188) doesn't close the list when item is clicked.

**Comment by danrabbit** [comment]
Just noting that you can now swipe away notifications without closing the indicator, but we probably also want to have a mouse-accessible way to do this

**Comment by danrabbit** [comment]
This is now fixed! We added close buttons
