### ISSUE TITLE
Clicking on a notification clears it without opening it!

### ISSUE THREAD

**Issue by MIGxMIG** [elementary/wingpanel-indicator-notifications#104]
Clicking on a notification should open it then clears it. If we want to just clear it then we click on the X button next to it.

**Comment by rohitpaulk** [comment]
I can confirm the same, at least with AppCenter notifications. Clicking on them does nothing, I'd expect it to open the app.

**Comment by rohitpaulk** [comment]
Got a notification from AppCenter today, and clicking that did open AppCenter. Maybe this got fixed in a recent release?

**Comment by rohitpaulk** [comment]
Ah, sorry - my mistake, that notification was a bubble, not part of the indicator.
