### ISSUE TITLE
Expand menu if there is one notification with more than one line of text

### ISSUE THREAD

**Issue by hanaral** [elementary/wingpanel-indicator-notifications#112]
## Prerequisites
- [ ] I have searched open and closed issues for duplicates.

## Feature
If a single notification has multiple lines of text, the notification drop down does not expand, and you have to scroll to see the cut off text:
![image](https://user-images.githubusercontent.com/58219504/81422026-518ca280-914a-11ea-80fc-915395b44c07.png)

**Describe the solution you'd like**
If there is only one notification, the drop down should still expand at least halfway if the notification has more than 1 line of text (so that both the app name and text is visible).

**Comment by danirabbit** [comment]
Closing since this is for a quite old version of the indicator and the design has changed significantly
