### ISSUE TITLE
[Bug] Missing notification-icon

### ISSUE THREAD

**Issue by paledega** [elementary/wingpanel-indicator-notifications#117]
Icon theme: Adwaita
![Screenshot from 2020-06-07 16-39-47](https://user-images.githubusercontent.com/38860643/83974539-845abf80-a8dd-11ea-941a-abbee4503fbd.png)

**Comment by paledega** [comment]
Icon only shown with elementary icon theme 

We must add fallback icon

**Comment by danrabbit** [comment]
Closing as “out of scope”. Pantheon is intended to be used with the elementary icon set.

**Comment by paledega** [comment]
I found sollution:

copy notification-new-symbolic.svg and notification-symbolic.svg from elementary icon theme to hicolor

packagers can embed 2 files in notification indicator package.

**Comment by paledega** [comment]
https://gitlab.com/sulinos/repositories/SulinRepository/-/commit/3d3d0efdcc16fc3802600e0c4d2884d2f120296b
