### ISSUE TITLE
Swipe to dismiss notification doesn't follow natural scroll preferences

### ISSUE THREAD

**Issue by JoseExposito** [elementary/wingpanel-indicator-notifications#171]
## What Happened

Dismissing a notification with a 2 finger swipe always show the animation like if natural scroll is enabled.

## Expected Behavior

Natural scrolling preferences should be used.

## Platform Information

elementary OS 6 Next, up to date.

**Comment by cassidyjames** [comment]
Hm, it seems to be following it for me here. Though with Natural scrolling off, it feels super backwards to me :stuck_out_tongue:

**Comment by danrabbit** [comment]
We don't do any custom event handling here, so if there is an issue it would be with LibHandy. So, this is out of scope :)
