### ISSUE TITLE
Add tooltip to indicator icon

### ISSUE THREAD

**Issue by cassidyjames** [elementary/wingpanel-indicator-notifications#173]
## Problem

A tooltip could provide some extra information before clicking or just some quicker information that feels faster to access without clicking at all.

## Proposal

Add a tooltip with the status it is indicating, and maybe the middle-click action:

>**No new notifications**
>Middle-click to enable Do Not Disturb

or

>**13 new notifications from 3 apps**
>Middle-click to enable Do Not Disturb

or

>**Do Not Disturb enabled**
>Middle-click to disable

## Prior Art

We added a tooltip to Applications Menu with a longer description and keyboard shortcuts.

**Comment by pongloongyeat** [comment]
I have a PR ready for this but I'm just unsure how to set the accelerator for a mouse click. Granite.markup_accel_tooltip takes **keyboard** accelerators.
