### ISSUE TITLE
Panel crashes when clearing all notifications

### ISSUE THREAD

**Issue by pongloongyeat** [elementary/wingpanel-indicator-notifications#174]
## What Happened
As title says.

## Expected Behavior
Shouldn't crash.

## Steps to Reproduce
1. Open notifications popover
2. Click clear all notifications.

I can't successfully reproduce this 100% of the time but I've been noticing this quite a lot lately.

### Logs

I don't really understand the logs. Seems to be a segmentation fault caused by wingpanel-indicator-power I think?
```bash
(captive-login:81772): dconf-DEBUG: 02:21:00.037: sync
(wingpanel:79242): dconf-DEBUG: 02:23:01.862: watch_fast: "/io/elementary/desktop/wingpanel/power/" (establishing: 0, active: 1)
** (wingpanel:79242): DEBUG: 02:23:01.869: Device.vala:174: Connection to UPower device established
** (wingpanel:79242): DEBUG: 02:23:01.872: Indicator.vala:114: Icon changed to "battery-full-charged-symbolic"
** (wingpanel:79242): DEBUG: 02:23:01.879: Device.vala:174: Connection to UPower device established
** (wingpanel:79242): DEBUG: 02:23:01.921: Device.vala:174: Connection to UPower device established
** (wingpanel:79242): DEBUG: 02:23:01.925: Device.vala:174: Connection to UPower device established
** (wingpanel:79242): DEBUG: 02:23:01.927: DeviceManager.vala:140: Device "/org/freedesktop/UPower/devices/battery_BAT1" registered
** (wingpanel:79242): DEBUG: 02:23:01.933: Monitor.vala:42: Initialising process monitor.
(wingpanel:79242): dconf-DEBUG: 02:23:03.695: change_fast
(wingpanel:79242): dconf-DEBUG: 02:23:03.695: change_notify: /io/elementary/desktop/wingpanel/power/show-percentage
(wingpanel:79242): dconf-DEBUG: 02:23:04.911: change_fast
(wingpanel:79242): dconf-DEBUG: 02:23:04.912: change_notify: /io/elementary/desktop/wingpanel/power/show-percentage
Segmentation fault
```

## Platform Information

eOS6 daily. wingpanel-indicator-network on my own branch at the moment but I've noticed crashes prior to this.

**Comment by vjr** [comment]
I'm able to reproduce this issue by running `notify-send test` many times, like around 20-30 times then clicking the clear-all button quickly after popping open the indicator.

I tried building with and installing debug symbols and have gotten the following output but I can't figure out what's happening, here is the snippet:

`#0  0x00007ffff7c73669 in g_type_check_instance_is_fundamentally_a
    (type_instance=type_instance@entry=0x200000002, fundamental_type=fundamental_type@entry=0x50 [GObject]) at ../../../gobject/gtype.c:4026
#1  0x00007ffff7c50942 in g_object_ref (_object=0x200000002) at ../../../gobject/gobject.c:3365
#2  0x00007ffff7ba745c in gee_hash_map_value_iterator_real_foreach (f_target=<optimized out>, f=<optimized out>, base=<optimized out>) at hashmap.c:4840
#3  gee_hash_map_value_iterator_real_foreach (base=0x555555dde5f0, f=0x7fffecd75e4b <___lambda17__gee_forall_func>, f_target=0x555555688490)
    at hashmap.c:4792
#4  0x00007ffff7b765a5 in gee_abstract_collection_real_foreach
    (self=<optimized out>, f=0x7fffecd75e4b <___lambda17__gee_forall_func>, f_target=0x555555688490) at abstractcollection.c:436
#5  0x00007fffecd75ef1 in notifications_notifications_list_clear_all (self=0x555555688490 [NotificationsNotificationsList])
    at ../src/Widgets/NotificationsList.vala:83
#6  0x00007fffecd733a8 in ___lambda22_ (self=0x5555558582b0 [NotificationsIndicator]) at ../src/Indicator.vala:135
#7  0x00007fffecd73403 in ____lambda22__gtk_button_clicked (_sender=0x555555d22b20 [GtkModelButton], self=0x5555558582b0) at ../src/Indicator.vala:135
#11 0x00007ffff7c6b0d3 in <emit signal ??? on instance 0x555555d22b20 [GtkModelButton]>
    (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>) at ../../../gobject/gsignal.c:3554
    #8  0x00007ffff7c4b802 in g_closure_invoke
    (closure=0x555555c20f10, return_value=0x0, n_param_values=1, param_values=0x7fffffffc8c0, invocation_hint=0x7fffffffc840)
    at ../../../gobject/gclosure.c:810
    #9  0x00007ffff7c5f814 in signal_emit_unlocked_R
    (node=node@entry=0x7fffe4013690, detail=detail@entry=0, instance=instance@entry=0x555555d22b20, emission_return=emission_return@entry=0x0, instance_and_params=instance_and_params@entry=0x7fffffffc8c0) at ../../../gobject/gsignal.c:3742
    #10 0x00007ffff7c6ab9e in g_signal_emit_valist
    (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7fffffffca70) at ../../../gobject/gsignal.c:3498
#12 0x00007ffff74f32ae in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#13 0x00007ffff74f3318 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#17 0x00007ffff7c6b0d3 in <emit signal ??? on instance 0x555555d22b20 [GtkModelButton]>
    (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>) at ../../../gobject/gsignal.c:3554
    #14 0x00007ffff7c4b802 in g_closure_invoke
    (closure=0x55555569e5c0, return_value=0x0, n_param_values=1, param_values=0x7fffffffcd80, invocation_hint=0x7fffffffcd00)
    at ../../../gobject/gclosure.c:810
    #15 0x00007ffff7c5f962 in signal_emit_unlocked_R
    (node=node@entry=0x5555556beb70, detail=detail@entry=0, instance=instance@entry=0x555555d22b20, emission_return=emission_return@entry=0x0, instance_and_params=instance_and_params@entry=0x7fffffffcd80) at ../../../gobject/gsignal.c:3672
    #16 0x00007ffff7c6ab9e in g_signal_emit_valist
    (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7fffffffcf30) at ../../../gobject/gsignal.c:3498
#18 0x00007ffff74f1754 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#19 0x00007ffff77a2ae1 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#20 0x00007ffff7c4ba56 in _g_closure_invoke_va
    (closure=0x555555a3b640, return_value=0x0, instance=0x555555de8110, args=0x7fffffffd280, n_params=3, param_types=0x5555558029e0)
    at ../../../gobject/gclosure.c:873
#21 0x00007ffff7c6ab28 in g_signal_emit_valist (instance=0x555555de8110, signal_id=<optimized out>, detail=0, var_args=var_args@entry=0x7fffffffd280)
    at ../../../gobject/gsignal.c:3407
#22 0x00007ffff7c6b0d3 in g_signal_emit (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>) at ../../../gobject/gsignal.c:3554
#23 0x00007ffff75b9fcc in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#24 0x00007ffff7c4ec56 in g_cclosure_marshal_VOID__BOXEDv
    (closure=0x55555571d6d0, return_value=<optimized out>, instance=<optimized out>, args=<optimized out>, marshal_data=<optimized out>, n_params=<optimized out>, param_types=0x555555715e50) at ../../../gobject/gmarshal.c:1686
#25 0x00007ffff7c4ba56 in _g_closure_invoke_va
    (closure=0x55555571d6d0, return_value=0x0, instance=0x555555de8110, args=0x7fffffffd630, n_params=1, param_types=0x555555715e50)
    at ../../../gobject/gclosure.c:873
#26 0x00007ffff7c6ab28 in g_signal_emit_valist (instance=0x555555de8110, signal_id=<optimized out>, detail=0, var_args=var_args@entry=0x7fffffffd630)
    at ../../../gobject/gsignal.c:3407
#27 0x00007ffff7c6b0d3 in g_signal_emit (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>) at ../../../gobject/gsignal.c:3554
#28 0x00007ffff75b7012 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#29 0x00007ffff75b865b in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#30 0x00007ffff75bb646 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#31 0x00007ffff7582bb0 in gtk_event_controller_handle_event () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#32 0x00007ffff774516d in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#33 0x00007ffff779c5ef in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#34 0x00007ffff7c4ba56 in _g_closure_invoke_va
    (closure=0x5555555ff4b0, return_value=0x7fffffffd9d0, instance=0x555555d22b20, args=0x7fffffffdaa0, n_params=1, param_types=0x5555555ff4e0)
    at ../../../gobject/gclosure.c:873
#35 0x00007ffff7c69dd1 in g_signal_emit_valist
    (instance=0x555555d22b20, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7fffffffdaa0) at ../../../gobject/gsignal.c:3407
#36 0x00007ffff7c6b0d3 in g_signal_emit (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>) at ../../../gobject/gsignal.c:3554
#37 0x00007ffff7746c23 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#38 0x00007ffff7602128 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#39 0x00007ffff76043db in gtk_main_do_event () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#40 0x00007ffff72eaf79 in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#41 0x00007ffff731e106 in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#42 0x00007ffff7ec9fbd in g_main_dispatch (context=0x555555590830) at ../../../glib/gmain.c:3309
#43 g_main_context_dispatch (context=context@entry=0x555555590830) at ../../../glib/gmain.c:3974
#44 0x00007ffff7eca240 in g_main_context_iterate
    (context=context@entry=0x555555590830, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../../../glib/gmain.c:4047
#45 0x00007ffff7eca2e3 in g_main_context_iteration (context=context@entry=0x555555590830, may_block=may_block@entry=1) at ../../../glib/gmain.c:4108
#46 0x00007ffff7d79fd5 in g_application_run (application=0x55555558c100 [WingpanelApplication], argc=<optimized out>, argv=<optimized out>)
    at ../../../gio/gapplication.c:2559
#47 0x0000555555561941 in wingpanel_application_main (args=0x7fffffffdf18, args_length1=1) at src/25a6634@@wingpanel@exe/Application.c:929
#48 0x00007ffff70570b3 in __libc_start_main (main=
    0x55555555df20 <main>, argc=1, argv=0x7fffffffdf18, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdf08)
    at ../csu/libc-start.c:308
#49 0x000055555555df6e in _start () at src/25a6634@@wingpanel@exe/Application.c:921`

**Comment by jeremypw** [comment]
Pressing the clear all button seems to trigger a whole slew of signals - even with only on notification in the list the entry is removed twice and the session file contents cleared three times (!).  I suspect with a lot of entries at some point something gets accessed after it has been destroyed.
