### ISSUE TITLE
Screenshot looks bad with dark mode on GitHub

### ISSUE THREAD

**Issue by ryonakano** [elementary/wingpanel-indicator-notifications#176]
![Screenshot from 2020-12-18 14-21-21](https://user-images.githubusercontent.com/26003928/102578278-2553ee00-413d-11eb-9242-fd185bb68784.png)

This is because we take screenshots with "grab the current window" in Screenshot. We may want to take screenshots with selected area with white wallpaper instead.

**Comment by cassidyjames** [comment]
I wonder if we can use CSS to switch to a dark style screenshot? :thinking: But yeah we could probably do _something_ better here.

**Comment by MrPotatoBobx** [comment]
Maybe an opeque panel would fix the issue?

![screenshot](https://user-images.githubusercontent.com/63403023/116792234-03de1800-aac8-11eb-95ef-aa563256239c.png)

**Comment by ryonakano** [comment]
Fixed in the latest release.
