### ISSUE TITLE
All notifications are grouped under "Other"

### ISSUE THREAD

**Issue by cassidyjames** [elementary/wingpanel-indicator-notifications#179]
## What Happened

When I get any notification, whether from AppCenter, Terminal, Sideload, or other apps, it is categorized under "Other" instead of the app name.

## Expected Behavior

Notifications are categorized by their app names

## Steps to Reproduce

1. Boot a recent elementary OS 6 build
2. Wait for a notification, e.g. from AppCenter
3. See it under "Other"

## Platform Information

elementary OS 6 daily build, fully updated as of today

**Comment by pongloongyeat** [comment]
Terminal task finished log:

```
Flags:   none
Version: 0
Serial:  78
Headers:
  path -> objectpath '/org/freedesktop/Notifications'
  interface -> 'org.freedesktop.Notifications'
  member -> 'Notify'
  destination -> 'org.freedesktop.Notifications'
  sender -> ':1.61'
  signature -> signature 'susssasa{sv}i'
Body: ('', uint32 0, 'utilities-terminal', 'Task finished', 'sleep 5', @as [], {'desktop-entry': <''>, 'urgency': <byte 0x01>}, -1)
UNIX File Descriptors:
  (none)
```

Here's a notification from one of my Files PR:

```
Flags:   none
Version: 0
Serial:  88
Headers:
  path -> objectpath '/org/freedesktop/Notifications'
  interface -> 'org.freedesktop.Notifications'
  member -> 'Notify'
  destination -> 'org.freedesktop.Notifications'
  sender -> ':1.61'
  signature -> signature 'susssasa{sv}i'
Body: ('', uint32 0, 'drive-removable-media-usb', 'Generic Flash Disk connected', 'With 2 volumes present', @as [], {'desktop-entry': <''>, 'urgency': <byte 0x01>}, -1)
UNIX File Descriptors:
  (none)
```

Doesn't seem like `desktop_id` ("desktop-entry.desktop") is valid so it's falling back to "gala-other.desktop".
