### ISSUE TITLE
The notification bubbles should go away when indicator is clicked

### ISSUE THREAD

**Issue by Loreno10** [elementary/wingpanel-indicator-notifications#207]
## What Happened
When some notification bubble pops up on the screen, and we open the Notifications panel from the wingpanel, the notification bubble covers the panel.
![image](https://user-images.githubusercontent.com/10273406/123461245-26347380-d5e9-11eb-94d0-d7667835a359.png).

## Expected Behavior
Since the Notifications Panel is all about notifications, I think the desktop notification should disappear as soon as I open the panel - I will see the same notification there anyway.

For comparison, i.e., on macOS when you open the notifications panel, it moves the on-desktop notification bubbles to the left, so that they do not cover the panel.
So another solution, a bit similar to macOS would be to move the notification bubbles down so that they do not cover the Notification Panel?

## Steps to Reproduce
Wait for some notification to pop up. While the notification is on screen, open the notification panel.

## Platform Information
eOS6 Beat 2

**Comment by Loreno10** [comment]
Oh, actually I see a similar report at https://github.com/elementary/wingpanel-indicator-notifications/issues/184.

**Comment by andirsun** [comment]
@Loreno10 yes its duplicated, please close the issue
