### ISSUE TITLE
Indicator active even when notifications cleared

### ISSUE THREAD

**Issue by kdwk** [elementary/wingpanel-indicator-notifications#214]
## What Happened

![Screenshot from 2021-07-18 09-30-33](https://user-images.githubusercontent.com/39268094/126053032-b3e0205c-5018-431c-8c32-03bd818ecdb7.png)

## Expected Behavior

The indicator icon reverts to the normal bell icon when notifications are cleared

## Steps to Reproduce

1. Get some notifications
2. Clear them all
3. Observe the indicator

## Platform Information

![Screenshot from 2021-07-14 10-55-34](https://user-images.githubusercontent.com/39268094/126053034-08c13763-19d9-4dbe-9e32-0407202ff722.png)

**Comment by jeremypw** [comment]
I could not reproduce this on Odin daily - the wingpanel indicator updated as expected on clearing all notifications.

**Comment by kdwk** [comment]
Bug seems to have fixed itself. No longer seeing this.
