### ISSUE TITLE
Enable notification action on notification center

### ISSUE THREAD

**Issue by taikio** [elementary/wingpanel-indicator-notifications#216]
## Problem

When a new notification is displayed I click on it and then an action is performed, however if instead of clicking on the notification when it appears I try to click on it within the notification center it just disappears from it without taking any action. I noticed this when I tried to click on a notification about updates and the appcenter didn't open.

## Proposal

I believe it would improve the user experience if notifications could perform an action when clicked within the notification center

## Prior Art

A good example would be the smartphone's OS notification center

**Comment by danirabbit** [comment]
Fixed in #263
