### ISSUE TITLE
Group notification to improve handling

### ISSUE THREAD

**Issue by andirsun** [elementary/wingpanel-indicator-notifications#217]
## Problem

I have tons of notifications per day, mostly from conversation in telegram and whatsapp and Its hard to see them with scroll.
![Screenshot from 2021-08-02 23-18-40](https://user-images.githubusercontent.com/22928302/127957120-673b362f-57a8-414f-861e-6f591e578820.png)

## Proposal

We could group  notifications by app or in a range of time (hours per example) and exapand them with with a click. I really like this behavior in mac os. 
![macos-big-sur-grouped-notifications-100851426-orig](https://user-images.githubusercontent.com/22928302/127957328-d3b30ad5-908b-4b05-88a9-326ccb7d3876.jpg)

**Comment by vjr** [comment]
Grouping would also make withdrawing notifications "cleaner" ? See https://github.com/elementary/wingpanel-indicator-notifications/issues/204

Currently appcenter notifications don't withdraw: https://github.com/elementary/appcenter/blob/master/src/Core/Client.vala#L86

I have some (ugly) local changes to use `Hdy.Deck` to gather all notifications from the same app ID but not worth creating a PR, someone with better Gtk UI chops could probably make quick work of this.
