### ISSUE TITLE
Ensure notification always have a title and body

### ISSUE THREAD

**Issue by danrabbit** [elementary/wingpanel-indicator-notifications#219]
## Problem

If a notification is sent with only a title, it's a bit off balance:

![Screenshot from 2021-08-19 12 32 19](https://user-images.githubusercontent.com/7277719/130132748-aad03d7f-9682-4d8b-b4b7-e36c54b92098.png)

## Proposal

If the notification only contains a title, we should use the title as body and the app name as title

## Prior Art

This is what we do in the server

**Comment by lorencinibrdev** [comment]
Did the changes here. Is this what you had in mind?

![image](https://user-images.githubusercontent.com/4778177/132465173-73fe42e0-f4f5-430a-9d84-0a439af519bf.png)

Won't this feel weird by showing the Application name twice (One on the grouping, another on the notification itself)?

Btw, tried reproducing that notification of your example, and failed. :D
