### ISSUE TITLE
Make clicking on notifications meaningful

### ISSUE THREAD

**Issue by ayoungethan** [elementary/wingpanel-indicator-notifications#239]
### What Happened?

When a notification for an app appears, it allows me to interact with it in three ways:
1. Close the specific notification using the "X" in the upper left corner of the notification
2. Clear all notifications using the dedicated button
3. Click on the specific notification

When I click on a notification, all it does is close it. This seems redundant.

### Steps to Reproduce

Just click on a notification. The notification disappears, and nothing else happens.

### Expected Behavior

When I click on a notification, I expect it to take me either to the app or the specific relevant dialog box. For example, if I get a notification from the AppCenter that updates are available, I expect that clicking on that notification will not only take me to the AppCenter, but also take me to the "installed software" tab of the app where the updates are actually listed.

It seems redundant and confusing to me that clicking on a notification does nothing except close the notification, especially when there are already two other more obvious and explicit means to get rid of an notification.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by danirabbit** [comment]
I believe this should be fixed by #263

Clicking the notification should try to launch the default action that was sent by the app to the notification server, or launch the app if none was set

**Comment by janxkoci** [comment]
That only works with a few apps, most do nothing, as OP describes.
