### ISSUE TITLE
Wrapped notifications cause overlap with separator

### ISSUE THREAD

**Issue by cassidyjames** [elementary/wingpanel-indicator-notifications#24]
As reported (on the wrong project) at https://github.com/elementary/screenshot-tool/issues/16

![Screenshot from Launchpad](https://launchpadlibrarian.net/312611233/photo_2017-03-26_17-43-29.jpg)

**Comment by megatux** [comment]
This issue annoys me alot. It's been present for me for probably a year.

**Comment by matzipan** [comment]
@megatux elementary is by no means perfect and we need every bit of help we can get to make it better. So please consider [getting involved](https://elementary.io/get-involved) or [placing a bounty](https://www.bountysource.com/teams/elementary).

**Comment by deyvisonrocha** [comment]
Happens with me too. 

![image](https://user-images.githubusercontent.com/686067/33666707-9e3d7df0-da79-11e7-97af-15560bc0df88.png)

**Comment by danrabbit** [comment]
This seems to be fixed in master
