### ISSUE TITLE
Clear All Notifications can create non-removable notifications.

### ISSUE THREAD

**Issue by SuperRiderTH** [elementary/wingpanel-indicator-notifications#244]
### What Happened?

The Clear All Notifications button does not dismiss notifications, and leaves behind non-removable notifications.

Example with notifications attempting to be swiped away with trackpad, clicked on, "Clear All Notifications" not selectable:

![Screenshot from 2022-05-04 03 35 53](https://user-images.githubusercontent.com/5368844/166639787-11ad78ff-6597-4700-8138-635c3c19b420.png)

### Steps to Reproduce

1. Have notifications
2. Select Clear All Notifications.

https://user-images.githubusercontent.com/5368844/166834482-e426d0a6-59a7-415f-ac3f-cdddd78972fd.mp4

### Expected Behavior

Clear All Notifications should clear all notifications.

### OS Version

7.x (Early Access)

### Software Version

Latest release (I have run all updates)

**Comment by jeremypw** [comment]
I haven't managed to get the pink "Delete" placeholder entry to persist after swiping away a notification yet.  Is it possible to give more detail how to achieve this?  These placeholders should be removed immediately after the swipe is completed (or revert to the normal notification if the swipe is cancelled)

**Comment by SuperRiderTH** [comment]
After experimenting with it more, it is actually the Clear All Notifications button that is broken. Using that option will create notifications that can not be deleted.

**Comment by jeremypw** [comment]
Just experienced this issue on OS7 in relation to some (but not all) Slack app notifications.

**Comment by selwynorren** [comment]
Seems I have the same issue on Elementary OS 6.1 with all the latest updates installed

**Comment by jeremypw** [comment]
Probably due to https://github.com/elementary/wingpanel-indicator-notifications/pull/242 - which was one of mine :frowning: - I'll investigate.
