### ISSUE TITLE
Notification count in tooltip sometimes inaccurate

### ISSUE THREAD

**Issue by jeremypw** [elementary/wingpanel-indicator-notifications#256]
### What Happened?

After clearing all notifications and closing the popover, a further notification was sent.  The indicator tooltip continued to show "No notifications" even after opening and closing the popover to confirm that the list did in fact contain one notification.

### Steps to Reproduce

* Clear notifications
* Send a test notification
* Check tooltip

### Expected Behavior

The tooltip shows the true number of notifications in the list.

### OS Version

7.x (Horus)

### Software Version

Compiled from git

**Comment by lenemter** [comment]
@jeremypw Was this fixed in https://github.com/elementary/wingpanel-indicator-notifications/pull/243?

**Comment by jeremypw** [comment]
Closing as was fixed in #243
