### ISSUE TITLE
Improve UX

### ISSUE THREAD

**Issue by alainhuntt** [elementary/wingpanel-indicator-notifications#26]
When activating the notifications for some song, there are moments where I feel the need to change the song to the instate, but I am uncomfortable because the notification is still active.
![captura de pantalla de 2017-08-07 08-22-21](https://user-images.githubusercontent.com/29526231/29029752-55517932-7b4e-11e7-8fa7-ecaadf9ef18e.png)
**Solution**: you could create a shortcut in the active notification to change song, or in the best of cases to be able to choose which action to choose.

**Comment by alons45** [comment]
Transparent notification (when the click is over) a la Ubuntu / Unity 7

**Comment by cassidyjames** [comment]
This is an issue that should be solved by the window manager by deferring or moving notifications when indicators are open. Filed at https://github.com/elementary/gala/issues/91
