### ISSUE TITLE
Ephemeral notifications

### ISSUE THREAD

**Issue by joedborg** [elementary/wingpanel-indicator-notifications#37]
Just an idea for a feature request.  Would the idea of "ephemeral requests" be a good one?  What I mean by this is notifications that are only useful for a short period of time (or even only for the bubble to appear and not entered into the backlog).  For example, with music you probably don't care about what you've been listening to, just what's started to play.

Perhaps this already exists and just not supported by this particular app?

![screenshot from 2018-03-05 10-35-21](https://user-images.githubusercontent.com/1426404/36970623-1b6b3a6a-2061-11e8-840f-dcb9e3979801.png)

Thanks!

**Comment by tintou** [comment]
Yes it's already supported, it's just that Spotify (and most electron apps) have a poor support of notifications...

**Comment by davidmhewitt** [comment]
Also, see here for a modification you can make to Spotify's desktop file to make it slightly nicer. Obviously not a permanent solution as Spotify may overwrite your modifications

https://elementaryos.stackexchange.com/a/13336/9699

**Comment by joedborg** [comment]
Thanks @davidmhewitt, I looked at writing a native Spotify client for Elementary but it looks like a dead end with the dropping of `libspotify`.
