### ISSUE TITLE
Clementine: Turning off sound notification when music changes is not working

### ISSUE THREAD

**Issue by ghost** [elementary/wingpanel-indicator-notifications#46]
I made a few tests. Turned **off** the notification sound when the music changes but I still hear the sound when the music changes using Clementine music player.

This is not happening with the default music player and Melody player, just Clementine, I didn't test other players.

**Comment by ssspacez** [comment]
This happens with **Spotify snap** too.

**Comment by zeebok** [comment]
For me this *does* happen with the default Music app.

**Comment by peteruithoven** [comment]
This sounds like the same issue as: https://github.com/elementary/wingpanel-indicator-notifications/issues/61

> @AndrewVos the only way we can reliably associate notifications with apps is if the application uses the notifications API correctly. If the notifications are not being associated with their app, then the app is not using the API correctly and the amount of configuration is limited.

Please reach out to the developer of those apps.
