### ISSUE TITLE
Notifications are not persisted unless the indicator has been opened at least once

### ISSUE THREAD

**Issue by cassidyjames** [elementary/wingpanel-indicator-notifications#48]
_From @ryonakano on September 6, 2018 4:24_

## Actual Behavior & Steps to reproduce

Power on your Juno Beta1 and use some app that uses notifications, like Music or Mail.

![screenshot from 2018-09-06 13-06-31](https://user-images.githubusercontent.com/26003928/45134644-8b1f4480-b1d6-11e8-860f-57846b8ad1f2.png)

Notifications appear as bubbles but are not stored in the notification indicator, like this screenshot.

![screenshot from 2018-09-06 13-06-46](https://user-images.githubusercontent.com/26003928/45134645-8e1a3500-b1d6-11e8-90c7-e36e20436450.png)

They are stored in the notification indicator after the notification indicator is opened.

## Expected Behavior

Notifications should appear as bubbles and be stored in the notification indicator even if users don't open the notification indicator.

**Comment by cassidyjames** [comment]
@danrabbit mentioned this is likely due to a performance optimization for indicators that @donadigo knows more about?

**Comment by donadigo** [comment]
@cassidyjames yes, that might be an issue here, let me take a look at the issue.

**Comment by ryonakano** [comment]
Thank you everyone! :smile:

**Comment by cassidyjames** [comment]
@ryonakano thanks for noticing and reporting the issue!
