### ISSUE TITLE
Phantom notification

### ISSUE THREAD

**Issue by Djaler** [elementary/wingpanel-indicator-notifications#51]
Sometimes after reboot I see a red dot in notification indicator. But when I open indicator, the dot disappear, and here are no notifications.

I can't always reproduce this, but it happens very often for the last time.
You can see this by the link https://youtu.be/4m2A_FA9030

**Comment by Djaler** [comment]
Also, this null looks suspiciously too. https://github.com/elementary/wingpanel-indicator-notifications/blob/master/src/Services/NotificationsMonitor.vala#L109

**Comment by GammaGames** [comment]
I also have this, it shows up after every reboot.

![image](https://user-images.githubusercontent.com/7832163/46988722-32857600-d0b7-11e8-889d-4c0488e216da.png)
![image](https://user-images.githubusercontent.com/7832163/46988730-39ac8400-d0b7-11e8-87f6-8f573e0da0dd.png)
