### ISSUE TITLE
Notification time is not localized

### ISSUE THREAD

**Issue by welaq** [elementary/wingpanel-indicator-notifications#52]
On Juno beta 2.
When notification appeared now the word "now" is localized (maybe because it comes from wingpanel-indicator itself) and when notification appeared 3 or 15 minutes ago the string "15m ago" is not localized (I guess the string comes from granite?). I'm using Lithuanian language, all strings are translated for a long time.
See screenshot.
![ekrano nuotrauka is 2018-09-29 12-31-55](https://user-images.githubusercontent.com/28876465/46244191-de567280-c3e3-11e8-9481-d4cf250f8ed0.png)

**Comment by danrabbit** [comment]
This should be fixed. We've had a release of Granite with the translated strings included. OP, can you still reproduce?
