### ISSUE TITLE
Bell indicator stays unread when source application clears notifications

### ISSUE THREAD

**Issue by blaknite** [elementary/wingpanel-indicator-notifications#55]
This is related to #48, but not fixed by #49.

When an application creates and then clears a notification the bell indicator still shows as unread. When you open the indicator panel there are no notifications present. The unread state persists until the panel is opened. This only occurs if the indicator panel has not yet been opened.

![screenshot from 2018-10-27 11-23-23](https://user-images.githubusercontent.com/1002901/47597891-ae4ac100-d9db-11e8-81b2-d4fa2e6d9ca8.png)
![screenshot from 2018-10-27 11-22-16](https://user-images.githubusercontent.com/1002901/47597893-b276de80-d9db-11e8-85d1-a7bce65c6766.png)

**Comment by donadigo** [comment]
We are currently investigating this here: https://github.com/elementary/wingpanel-indicator-notifications/issues/51. This is a duplicate.
