### ISSUE TITLE
The character ' is not rendered correctly

### ISSUE THREAD

**Issue by miyoyo** [elementary/wingpanel-indicator-notifications#58]
This character (') is not rendered correctly when sent by discord
(However it does work with notify-send)
 

It's rendered as `&#39;`

**Comment by EbonJaeger** [comment]
I've fixed this locally (and will PR the fix), but it only seems to work for the notification popover. I haven't found where it is set for the notification popup itself yet.

**Comment by donadigo** [comment]
@EbonJaeger it's here: https://github.com/elementary/gala/blob/master/plugins/notify/NormalNotification.vala#L36.

**Comment by EbonJaeger** [comment]
@donadigo Ah, thanks!
