### ISSUE TITLE
Notification dots can't be hidden for apps not using the API correctly

### ISSUE THREAD

**Issue by AndrewVos** [elementary/wingpanel-indicator-notifications#61]
I'm trying to disable the red dots that appear when Spotify changes songs.

I followed the steps here:

https://elementaryos.stackexchange.com/questions/13333/is-it-possible-to-hide-notifications-for-a-specific-app

![image](https://user-images.githubusercontent.com/363618/51246705-e6cabd00-1982-11e9-8e66-1b900bd7d0dc.png)

But I'm still seeing the red dots.

![image](https://user-images.githubusercontent.com/363618/51246734-f8ac6000-1982-11e9-9dea-ce83a7616ea5.png)

Perhaps I am misunderstanding what those settings mean?

From the UX I expect the "Show missed notifications" to mean "the red dots". Is this the case?

I'm using the latest release of Juno. I have updated and upgraded the system.

**Comment by AndrewVos** [comment]
I just noticed that these appear as `Other`. Is there a way I can make them show up as `Spotify`.

Has a feature been considered to allow configuring applications even if they don't include `X-GNOME-UsesNotifications=true`?

**Comment by cassidyjames** [comment]
@AndrewVos the only way we can reliably associate notifications with apps is if the application uses the notifications API correctly. If the notifications are not being associated with their app, then the app is not using the API correctly and the amount of configuration is limited.
