### ISSUE TITLE
Notifications don't overlay on top of (some?) fullscreen apps

### ISSUE THREAD

**Issue by uncertainquark** [elementary/wingpanel-indicator-notifications#65]
I miss notifications in certain fullscreen apps like MPV, because the notification doesn't overlay on them. I would think that crucial notifications like "Battery is low" would take priority over any fullscreen apps. Is this by design or some apps' specific?

**Comment by peteruithoven** [comment]
Thanks for the report! I'm afraid this is a duplicate of https://github.com/elementary/gala/issues/134
